# Generated by Django 4.2.10 on 2024-03-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Blogpost",
        ),
    ]
