# Generated by Django 4.2.10 on 2024-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_blog_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="chead0",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead1",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead2",
            field=models.CharField(default="", max_length=5000),
        ),
    ]
