# Generated by Django 4.2.10 on 2024-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="orders",
            name="items_json",
            field=models.CharField(default="", max_length=5000),
        ),
    ]
