# Generated by Django 4.2.10 on 2024-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_orders_address_alter_orders_items_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="zip_code",
            field=models.IntegerField(max_length=100),
        ),
    ]
