# Generated by Django 4.2.10 on 2024-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_orders_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="zip_code",
            field=models.IntegerField(default=0),
        ),
    ]
