# Generated by Django 4.2.10 on 2024-02-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_orders_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="items_json",
            field=models.CharField(max_length=5000),
        ),
    ]
