# Generated by Django 4.2.10 on 2024-02-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_orders_items_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default=0)),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
