# Generated by Django 4.2.10 on 2024-03-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_orders_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
